### PR TITLE
RU Update!

### PR DESCRIPTION
**Pull request by TheVizzy**
Fix buggy translate. And now i translate Ru.lang :)

### CODE REVIEW

**Comment by amadornes** [comment]
The lines with a double comment are there for a reason: So things that aren't localized in a language are directly inherited from en_US.lang and get updated if that one changes. By forcing localizations this way, if we ever update them in en_US.lang and they are not translated to a language, they'll be outdated. Please fix this and it'll be merged :)

**Comment by TheVizzy** [comment]
Whats line with double comment? what can I fix?

**Comment by amadornes** [comment]
If you check the changed files you'll see you replaced a bunch of lines that started with "##" with their english equivalents from en_US. Those are there so the translations that aren't done fall back to the default ones and aren't hardcoded. What I'd like you to do is to update the pull request with those hardcoded translations replaced by what was there before and only leave uncommented the ones which are actually translated to russian :)

**Comment by TheVizzy** [comment]
ok

**Comment by TheVizzy** [comment]
Update! And last my translate I save on PC)

**Comment by amadornes** [comment]
Thanks! You missed a couple of translations in English but it should be okay for now :)

**Pull request merged**
