### PR TITLE
ASM and achievements

### PR DESCRIPTION
**Pull request by hilburn**
Need to add:
-Dfml.coreMods.load=com.bluepowermod.asm.LoadingPlugin
to VM arguments for it to build in dev environment

### CODE REVIEW

**Comment by iTitus** [comment]
Aren't there events for this? ASM is like a broadaxe where a precise tool would be better...

**Comment by Parker8283** [comment]
Yea, there are much better ways to do this than ASM.

**Comment by hilburn** [comment]
No there are not events for it, and I'm curious as to what you mean by broadaxe, it's operating on  bytecode level which is about as precise as it's possible to be.

Parker - such as?

**Comment by MineMaarten** [comment]
You can use the PlayerOpenContainer event to poll the inventory in the Enchantment table gui. Polling in this case shouldn't be too bad, as it's 36 slots, with the possibility of them being null, and you can stop looking when the stack has no nbt tag too. 

As a side note (it doesn't apply in this case), if we had to use ASM for something 'silly' as achievements,  imo we'd just have to go "ohh well, that's a bummer", and drop that achievement.

**Comment by MoreThanHidden** [comment]
No longer required this can be done with Advancements.

**Pull request closed without merging**
