### PR TITLE
Added Note Block Gate.

### PR DESCRIPTION
**Pull request by SoniEx2**
Currently doesn't have a GUI/a way to set the instrument. I don't know how to add an inventory to a gate.

### CODE REVIEW

**Comment by K-4U** [comment]
Not PR-ing from you, and most definately not unfinished PR's.

**Comment by SoniEx2** [comment]
> Not PR-ing from you

Why? :/

**Comment by SoniEx2** [comment]
Me being a bad person doesn't make me a bad coder :/

**Comment by GirafiStudios** [comment]
Well the first step, as K-4U said, would be to actually make a PR which is finished :p

**Comment by SoniEx2** [comment]
How do I add an inventory to a gate?

**Comment by GirafiStudios** [comment]
I don't know. Looks how it's done for the other gates.

**Comment by MrKickkiller** [comment]
@GirafiStudios: I don't think there are any gates with Inventories so far

**Comment by GirafiStudios** [comment]
I thought he meant GUIs :p

**Comment by MrKickkiller** [comment]
@SoniEx2 Don't forget the licensing.

**Comment by MrKickkiller** [comment]
@GirafiStudios, he'll need both.
But there are gates with GUI's

**Comment by SoniEx2** [comment]
@MrKickkiller The licensing?

**Comment by MrKickkiller** [comment]
@SoniEx2 :https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/block/BlockContainerBase.java#L1-L16

**Comment by SoniEx2** [comment]
@MrKickkiller Oh you can consider my contributions public domain.

Also, Minecraft's GUI system sucks >.> Looks like I'll have to workaround it.

**Pull request closed without merging**
